language: go

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -yq libpcap-dev 

env:
  - GIMME_OS=linux GIMME_ARCH=amd64

go:
  - master

install:
  - go get -d -v ./...

script:
  - go build -v ./...
